name: 'Infra - Dev'
on:
  push: 
    branches:
    - dev
    path:
    - 'terraform/*'
    - '.github/workflows/ci-dev.yml'
  pull_request:
    branches:
    - dev
    path:
    - 'terraform/*'
    - '.github/workflows/ci-dev.yml'

jobs:
  terraform:
    name: "Dev deploy"
    uses: "./.github/workflows/terraform-deploy.yaml"
    with:
      env: dev
      tf_state_bucket: cl-challenge-dev
      workload_identity_provider: projects/995096337479/locations/global/workloadIdentityPools/github-pool/* 
      service_account: provisioner-sa-dev@provisioner-377821.iam.gserviceaccount.com
    secrets: inherit
